# Generated by Django 3.2.9 on 2021-11-19 11:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=512), null=True, size=None),
        ),
    ]
