# Generated by Django 3.2.9 on 2021-11-22 14:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.ImageField(default=None, upload_to='images/'), default=list, size=None),
        ),
    ]
