# Generated by Django 3.2.9 on 2021-11-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211123_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default='user_profile.png', upload_to='images/'),
        ),
    ]
