# Generated by Django 3.2.9 on 2021-12-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_uploadimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text_markdown',
            field=models.TextField(default=''),
        ),
    ]
